import * as THREE from "three";
import { orbitPointFromSample, unwrapMercatorX, type OrbitDefinition } from "./orbitMath";

const EARTH_RADIUS = 8192 / (2 * Math.PI);
const OCCLUSION = `float earthVisibility(vec3 point,vec3 camera){vec3 ray=camera-point;float ray2=dot(ray,ray);float t=ray2==0.?0.:clamp(-dot(point,ray)/ray2,0.,1.);float clearance=length(point+t*ray);return smoothstep(${(EARTH_RADIUS - .005).toFixed(12)},${EARTH_RADIUS.toFixed(12)},clearance);}`;
const VERT = `attribute vec3 aEcef;uniform mat4 uGlobeToMerc;uniform float uTransition;uniform vec3 uCameraEcef;varying float vVisibility;${OCCLUSION} void main(){vec3 globeMerc=(uGlobeToMerc*vec4(aEcef,1.)).xyz;vec3 world=mix(globeMerc,position,uTransition);vVisibility=mix(earthVisibility(aEcef,uCameraEcef),1.,uTransition);gl_Position=projectionMatrix*modelViewMatrix*vec4(world,1.);}`;
const LINE_FRAG = `precision highp float;uniform vec3 uColor;uniform float uOpacity;varying float vVisibility;void main(){gl_FragColor=vec4(uColor,uOpacity*vVisibility);}`;
const SAT_VERT = `attribute vec3 aEcef;uniform mat4 uGlobeToMerc;uniform float uTransition;uniform vec3 uCameraEcef;uniform float uPixelRatio;uniform float uTime;varying float vVisibility;varying float vPulse;${OCCLUSION} void main(){vec3 globeMerc=(uGlobeToMerc*vec4(aEcef,1.)).xyz;vec3 world=mix(globeMerc,position,uTransition);vVisibility=mix(earthVisibility(aEcef,uCameraEcef),1.,uTransition);vPulse=.82+.18*sin(uTime*3.+aEcef.x*.01);gl_PointSize=18.*uPixelRatio*vPulse;gl_Position=projectionMatrix*modelViewMatrix*vec4(world,1.);}`;
const SAT_FRAG = `precision highp float;uniform vec3 uColor;varying float vVisibility;varying float vPulse;void main(){float d=length(gl_PointCoord-.5)*2.;if(d>1.)discard;float core=smoothstep(.28,0.,d);float glow=smoothstep(1.,.18,d)*.48;gl_FragColor=vec4(mix(uColor,vec3(1.),core),(core+glow)*vVisibility);}`;

interface Resource { orbit: OrbitDefinition; line: THREE.LineSegments; geometry: THREE.BufferGeometry; material: THREE.ShaderMaterial; }
export class OrbitScene {
  private renderer!: THREE.WebGLRenderer; private scene = new THREE.Scene(); private camera = new THREE.Camera();
  private satelliteGeometry: THREE.BufferGeometry | null = null; private satelliteMaterial: THREE.ShaderMaterial | null = null; private satellitePoints: THREE.Points | null = null;
  private orbitResources: Resource[] = []; private shellAltitudeScale = 1; private projection = new THREE.Matrix4(); private inverse = new THREE.Matrix4(); private cameraEcef = new THREE.Vector3();
  constructor(private readonly orbits: readonly OrbitDefinition[]) {}
  init(gl: WebGL2RenderingContext) { this.renderer = new THREE.WebGLRenderer({ canvas: gl.canvas as HTMLCanvasElement, context: gl, antialias: true }); this.renderer.autoClear = false; this.buildOrbits(); this.buildSatellites(); }
  private uniforms(color: string, opacity = 1) { return { uColor: { value: new THREE.Color(color) }, uOpacity: { value: opacity }, uGlobeToMerc: { value: new THREE.Matrix4() }, uTransition: { value: 1 }, uCameraEcef: { value: new THREE.Vector3() } }; }
  private lineAttributes(orbit: OrbitDefinition, scale: number) { const count = orbit.path.length - 1; const position = new Float32Array(count * 6); const ecef = new Float32Array(count * 6); for (let index = 0; index < count; index++) { const a = orbitPointFromSample(orbit.path[index]!, scale); const b = orbitPointFromSample(orbit.path[index + 1]!, scale); const flatB: [number, number, number] = [unwrapMercatorX(a.mercator[0], b.mercator[0]), b.mercator[1], b.mercator[2]]; position.set([...a.mercator, ...flatB], index * 6); ecef.set([...a.ecef, ...b.ecef], index * 6); } return { position, ecef }; }
  private buildOrbits() { for (const orbit of this.orbits) { const attributes = this.lineAttributes(orbit, this.shellAltitudeScale); const geometry = new THREE.BufferGeometry(); geometry.setAttribute("position", new THREE.BufferAttribute(attributes.position, 3)); geometry.setAttribute("aEcef", new THREE.BufferAttribute(attributes.ecef, 3)); geometry.boundingSphere = new THREE.Sphere(new THREE.Vector3(), Infinity); const material = new THREE.ShaderMaterial({ vertexShader: VERT, fragmentShader: LINE_FRAG, uniforms: this.uniforms(orbit.color, .82), transparent: true, depthTest: false, depthWrite: false, blending: THREE.AdditiveBlending }); const line = new THREE.LineSegments(geometry, material); line.frustumCulled = false; this.scene.add(line); this.orbitResources.push({ orbit, line, geometry, material }); } }
  private buildSatellites() { const moving = this.orbits.filter((orbit) => orbit.satelliteAt); if (!moving.length) return; const geometry = new THREE.BufferGeometry(); geometry.setAttribute("position", new THREE.BufferAttribute(new Float32Array(moving.length * 3), 3)); geometry.setAttribute("aEcef", new THREE.BufferAttribute(new Float32Array(moving.length * 3), 3)); geometry.boundingSphere = new THREE.Sphere(new THREE.Vector3(), Infinity); const material = new THREE.ShaderMaterial({ vertexShader: SAT_VERT, fragmentShader: SAT_FRAG, uniforms: { ...this.uniforms("#ffffff"), uPixelRatio: { value: Math.min(window.devicePixelRatio || 1, 2) }, uTime: { value: 0 } }, transparent: true, depthTest: false, depthWrite: false, blending: THREE.AdditiveBlending }); this.satelliteGeometry = geometry; this.satelliteMaterial = material; this.satellitePoints = new THREE.Points(geometry, material); this.satellitePoints.frustumCulled = false; this.scene.add(this.satellitePoints); }
  setFrame(matrix: number[], globeMatrix: number[] | null, transition: number, cameraMerc: { x: number; y: number; z: number } | null, simSec: number, altitudeScale: number) { this.camera.projectionMatrix.fromArray(matrix); if (globeMatrix && cameraMerc) { this.projection.fromArray(globeMatrix); this.inverse.copy(this.projection).invert(); this.cameraEcef.set(cameraMerc.x, cameraMerc.y, cameraMerc.z).applyMatrix4(this.inverse); } else { this.projection.identity(); this.cameraEcef.set(0, 0, 0); transition = 1; } if (altitudeScale !== this.shellAltitudeScale) { this.shellAltitudeScale = altitudeScale; for (const resource of this.orbitResources) { const attributes = this.lineAttributes(resource.orbit, altitudeScale); resource.geometry.setAttribute("position", new THREE.BufferAttribute(attributes.position, 3)); resource.geometry.setAttribute("aEcef", new THREE.BufferAttribute(attributes.ecef, 3)); } } for (const { material } of this.orbitResources) { material.uniforms.uGlobeToMerc.value.copy(this.projection); material.uniforms.uTransition.value = transition; material.uniforms.uCameraEcef.value.copy(this.cameraEcef); } if (this.satelliteGeometry && this.satelliteMaterial) { const position = this.satelliteGeometry.getAttribute("position") as THREE.BufferAttribute; const ecef = this.satelliteGeometry.getAttribute("aEcef") as THREE.BufferAttribute; let index = 0; for (const orbit of this.orbits) if (orbit.satelliteAt) { const point = orbitPointFromSample(orbit.satelliteAt(simSec), altitudeScale); position.setXYZ(index, ...point.mercator); ecef.setXYZ(index, ...point.ecef); index++; } position.needsUpdate = true; ecef.needsUpdate = true; this.satelliteMaterial.uniforms.uGlobeToMerc.value.copy(this.projection); this.satelliteMaterial.uniforms.uTransition.value = transition; this.satelliteMaterial.uniforms.uCameraEcef.value.copy(this.cameraEcef); this.satelliteMaterial.uniforms.uTime.value = simSec; } }
  render() { this.renderer.resetState(); this.renderer.render(this.scene, this.camera); this.renderer.resetState(); }
  dispose() { for (const resource of this.orbitResources) { this.scene.remove(resource.line); resource.geometry.dispose(); resource.material.dispose(); } this.orbitResources = []; if (this.satellitePoints) this.scene.remove(this.satellitePoints); this.satelliteGeometry?.dispose(); this.satelliteMaterial?.dispose(); this.renderer?.dispose(); }
}
